### ISSUE TITLE
Error en metodo mostrarGasto

### ISSUE THREAD

**Issue by borrajo21457** [borrajo21457/practica_dwec_gestor_presupuesto#1]
Hola  @pedroprieto:
Tengo un problema al pasar los test con el Método 'mostrarGasto' del objeto gasto que  recibe y devuelve los valores esperados , pero no pasa el test. Lo he revisado varias veces y soy incapaz de ver el fallo
![image](https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/assets/99894942/92412e0a-5f8a-48f5-9d0b-f41d37da286a)

**Comment by pedroprieto** [comment]
Buenas,

Generas una coma de más en el texto, después del símbolo del €. Ese es el problema.

Un saludo!
