### ISSUE TITLE
borrarEtiquetas_NOFUNCIONAFORMACORRECTA

### ISSUE THREAD

**Issue by borrajo21457** [borrajo21457/practica_dwec_gestor_presupuesto#2]
Hola @pedroprieto:
Te adjunto el código que no funciona. Este esta comentado(  /* borrarEtiquetas) al final de .js 
Lo he intentado hacer con includes , pero solo pasa el 1 test de borrado , cuando tiene que borrar el resto de etiquetas , no lo hace bien

**Comment by pedroprieto** [comment]
Buenas,

El código no está bien. Aquí:
https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/blob/ac7b2fcba0cad419877c08a2671e7621f5759dab/js/gestionPresupuesto.js#L158

pones un array como parámetro del `includes`. Es incorrecto: deberías poner un elemento, no el array entero.

Además, mediante `includes` solo sabes si un elemento está en el array: aunque lo hagas bien, solo sabes que dicho array incluye la etiqueta que estás buscando. Pero no sabes su posición para eliminarla del array. Tendrías que hacer algo como esto:

```js
 this.borrarEtiquetas = function (...etiquetasBorrar) {
  for (let i=0 ;i < etiquetasBorrar.length; i++) {   // Itero etiquetasBorrar, no this.etiquetas
    if (this.etiquetas.includes(etiquetasBorrar[i])) {  // Busco si incluye un elemento, no un array
	this.etiquetas.splice(this.etiquetas.indexOf(etiquetasBorrar[i]), 1);  // Localizo la posición de la etiqueta buscada dentro de this.etiquetas
    }
  }
};
```

Un saludo!!
