### ISSUE TITLE
Fallo en undefined

### ISSUE THREAD

**Issue by borrajo21457** [borrajo21457/practica_dwec_gestor_presupuesto#4]
hola @pedroprieto :
tengo el error que te he comentado por correo  del bucle de las etiquetas que dice que noes iterable

**Comment by pedroprieto** [comment]
Es `gasto.etiquetas`, claro. El problema está aquí:
https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/blob/7cb600a367690cbe5dcbdb534577cc8323dad900/js/generarDatosEstaticos.js#L12

Tienes varias líneas con el mismo fallo: `gstion` en vez de `gestion`.

Un saludo!

**Comment by borrajo21457** [comment]
ha cambiado el nombre y sigue dando el mismo fallo con gasto y con gasto.etiquetas.
![image](https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/assets/99894942/0d74c56f-95fd-42e7-a27f-993d0969a0fb)

**Comment by pedroprieto** [comment]
Claro, es que `gasto` es el objeto. Debes iterar `gasto.etiquetas` como te había dicho...

**Comment by pedroprieto** [comment]
De todos modos, el fallo importante está aquí:
https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/blob/7cb600a367690cbe5dcbdb534577cc8323dad900/js/generarDatosEstaticos.js#L37-L38

En tu código, `gasto` es un array de gastos. Es incorrecto: debes utilizar `mostrarGastoWeb` sobre un único `gasto`, no sobre la lista... Por tanto, te falta un bucle.

**Comment by borrajo21457** [comment]
hola @pedroprieto :
 Me ha surgido otro problema con 2 test , aparentemente el html esta bien , al menos cuando lo veo con el inspeccionar, al depurar no veo el fallo , pero aun asi no pasa los test por esto.
![image](https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/assets/99894942/2cd41362-f770-41f1-93d2-083b40eb3b20)

Pasa el test de los agrupar los meses pero no asi los del dia y ano y siendo el mismo codigo utilizado para su generacion , no logro entender xq falla

**Comment by borrajo21457** [comment]
arreglado era el swicht de obtenergastoAgrupacion.
![image](https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/assets/99894942/66a2aa21-d82f-4474-91ff-74a9d5848641)
