### ISSUE TITLE
Error : object is not extensibleº

### ISSUE THREAD

**Issue by borrajo21457** [borrajo21457/practica_dwec_gestor_presupuesto#5]
Buenas @pedroprieto.
Me ha surgido el siguiente error en la practica 5  y no se por donde tirar, 
1 -cuando llamo a la función nuevogasto y esta se ejecuta  de forma normal , cuando llega a gestionPresupuesto .Crear gasto( descripción ,......) y empieza su ejecucion
![image](https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/assets/99894942/c44c9d63-0741-4a19-8f8b-bba04814f206)

2-cuando pasa el primer parámetro (descripción) salta el siguiente error en el navegador

![image](https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/assets/99894942/6b357447-90ca-40d1-8218-311c57b7ce6b)
 3-y cuando ejecuto los test 

![image](https://github.com/borrajo21457/practica_dwec_gestor_presupuesto/assets/99894942/df1e621a-14cc-42e0-abc7-f650c31ff699)

**Comment by borrajo21457** [comment]
resuelto el fallo , el cual residía en no haber declarado el new al crear el gasto

**Comment by pedroprieto** [comment]
Perfecto pues. Bien hecho!! :clap:
