### ISSUE TITLE
error al borrar fomulario

### ISSUE THREAD

**Issue by borrajo21457** [borrajo21457/practica_dwec_gestor_presupuesto#6]
Buenas @pedroprieto..
Tras la explicación de por la mañana  he intentado realizar el ejercicio , pero sigo sin ser capaz de borrar el nodo del formulario al  evento- click de cancelar.
Por otro lado tambien tengo  mas problemas  en EditarHandleFormulario()

**Comment by pedroprieto** [comment]
Buenas, Óscar,

Esta tarde lo explico de nuevo en la tutoría. Un saludo!!
